package:
  name: ros-noetic-realsense2-camera
  version: 2.3.0
source:
  git_url: https://github.com/IntelRealSense/realsense-ros-release.git
  git_rev: release/noetic/realsense2_camera/2.3.0-1
  folder: ros-noetic-realsense2-camera/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 8
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - eigen
    - python
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-catkin
    - ros-noetic-cv-bridge
    - ros-noetic-ddynamic-reconfigure
    - ros-noetic-diagnostic-updater
    - ros-noetic-genmsg
    - ros-noetic-image-transport
    - ros-noetic-librealsense2
    - ros-noetic-message-runtime
    - ros-noetic-nav-msgs
    - ros-noetic-nodelet
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-std-srvs
    - ros-noetic-tf
  run:
    - eigen
    - python
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-cv-bridge
    - ros-noetic-ddynamic-reconfigure
    - ros-noetic-diagnostic-updater
    - ros-noetic-genmsg
    - ros-noetic-image-transport
    - ros-noetic-librealsense2
    - ros-noetic-message-runtime
    - ros-noetic-nav-msgs
    - ros-noetic-nodelet
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-std-srvs
    - ros-noetic-tf
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
