package:
  name: ros-noetic-tf2-web-republisher
  version: 0.3.2
source:
  git_url: https://github.com/RobotWebTools-release/tf2_web_republisher-release.git
  git_rev: release/noetic/tf2_web_republisher/0.3.2-3
  folder: ros-noetic-tf2-web-republisher/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 10
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
    - sel(build_platform != target_platform): pybind11
  host:
    - python
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-actionlib
    - ros-noetic-actionlib-msgs
    - ros-noetic-catkin
    - ros-noetic-geometry-msgs
    - ros-noetic-message-generation
    - ros-noetic-message-runtime
    - ros-noetic-roscpp
    - ros-noetic-rospy
    - ros-noetic-rostest
    - ros-noetic-tf
    - ros-noetic-tf2-ros
  run:
    - python
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-actionlib
    - ros-noetic-actionlib-msgs
    - ros-noetic-geometry-msgs
    - ros-noetic-message-runtime
    - ros-noetic-roscpp
    - ros-noetic-tf
    - ros-noetic-tf2-ros
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
