package:
  name: ros-noetic-fcl
  version: 0.6.1
source:
  git_url: https://github.com/ros-gbp/fcl-release.git
  git_rev: release/noetic/fcl/0.6.1-3
  folder: ros-noetic-fcl/src/work
  patches:
    - patch/ros-noetic-fcl.patch

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 4
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - cmake
    - eigen
    - libccd
    - python
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-octomap
  run:
    - eigen
    - libccd
    - python
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-catkin
    - ros-noetic-octomap
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
